# Generated by Django 5.0.1 on 2024-02-04 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eridosolutions', '0007_alter_order_total_amount_alter_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
